/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'
import { Route as DriversIdRouteImport } from './routes/drivers.$id'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VehiclesRoute,
} as any)
const DriversIdRoute = DriversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/drivers/$id': typeof DriversIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/drivers/$id': typeof DriversIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/drivers/$id': typeof DriversIdRoute
  '/vehicles/$id': typeof VehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/drivers'
    | '/login'
    | '/settings'
    | '/vehicles'
    | '/drivers/$id'
    | '/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/drivers'
    | '/login'
    | '/settings'
    | '/vehicles'
    | '/drivers/$id'
    | '/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/drivers'
    | '/login'
    | '/settings'
    | '/vehicles'
    | '/drivers/$id'
    | '/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
    '/drivers/$id': {
      id: '/drivers/$id'
      path: '/$id'
      fullPath: '/drivers/$id'
      preLoaderRoute: typeof DriversIdRouteImport
      parentRoute: typeof DriversRoute
    }
  }
}

interface DriversRouteChildren {
  DriversIdRoute: typeof DriversIdRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversIdRoute: DriversIdRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

interface VehiclesRouteChildren {
  VehiclesIdRoute: typeof VehiclesIdRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesIdRoute: VehiclesIdRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
